version: "3.9"
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '3307:3306'
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: test
    ports:
      - '5432:5432'    
  redis:
    image: redis:latest
    restart: unless-stopped
    args:
      - requirepass=$REDIS_PASSWORD
    ports:
      - '6379:6379'    
  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - '27017:27017'